# 1.Cargamos Datos

In [2]:
import pandas as pd

In [3]:
bulk_datos="/home/franciscojavier/Escritorio/TFG/scDEAL/data/ALL_expression.csv"
Bulk= pd.read_csv(bulk_datos, index_col=0)

In [4]:
Bulk.head()

,ST3GAL2,NOTCH2,GRPEL1,SHC2,MAGEA8,GNA14,KRTCAP2,CEP44,EHD2,UTP14C,...,CIAPIN1,PPFIA4,EPPK1,PSPC1,SLC30A2,RNF13,LAMC1,PITX3,SNX24,IL17RE
DATA.683665,5.144679,3.223748,8.473993,3.367309,3.228205,2.980778,8.523072,3.568470,3.205451,6.173123,...,5.794856,3.115977,3.236775,4.614050,3.334627,8.512252,5.454001,3.579842,3.719559,3.208217
DATA.683667,4.891309,4.978066,8.965003,7.597621,2.939119,3.127610,9.164316,3.226157,3.594308,4.838035,...,5.429998,3.165675,3.293903,3.833966,3.115850,9.187912,7.297341,3.350470,6.678025,3.106149
DATA.684052,4.185672,4.580091,8.342951,3.454799,2.940054,3.842441,8.715775,3.509050,2.943156,5.688459,...,6.166544,3.070921,4.455511,4.108411,3.080420,7.986220,7.260711,3.123496,4.627073,3.088657
DATA.684057,4.103474,4.681022,7.894892,6.939582,3.098473,4.450950,9.803396,3.732709,2.991773,6.523652,...,5.617250,3.318546,8.393024,3.945185,3.074119,8.615635,6.793222,3.177603,4.703124,3.081756
DATA.684059,4.564867,4.076783,8.136921,7.620565,3.111922,6.328582,8.801057,3.633442,3.264081,6.073701,...,5.948226,3.203330,3.278578,3.672100,3.171120,8.673449,6.673377,3.496695,5.829292,3.210553

In [5]:
print(f"El archivo tiene {Bulk.shape[0]} filas y {Bulk.shape[1]} columnas.")

El archivo tiene 1280 filas y 15962 columnas.

In [6]:
print(f"Número de genes: {Bulk.shape[1]}")
print(f"Número de muestras: {Bulk.shape[0]}")
print("Primeros 5 genes:", Bulk.columns[:5].tolist())

Número de genes: 15962
Número de muestras: 1280
Primeros 5 genes: ['ST3GAL2', 'NOTCH2', 'GRPEL1', 'SHC2', 'MAGEA8']

# CALCULAMOS VARIANZA

In [8]:
varianzas = Bulk.var(axis=0)  # varianza por columna (gen)
print(varianzas)

ST3GAL2    0.892848
NOTCH2     0.813878
GRPEL1     2.395445
SHC2       3.767519
MAGEA8     2.661780
             ...
RNF13      4.454409
LAMC1      2.325935
PITX3      2.773513
SNX24      1.557141
IL17RE     1.291969
Length: 15962, dtype: float64

In [9]:
top_20_porcentaje = int(len(varianzas) * 0.2) #Filtramos el top 20
genes_top = varianzas.sort_values(ascending=False).head(top_20_porcentaje).index
df_top_genes = Bulk[genes_top]

In [10]:
print(f"Genes seleccionados: {df_top_genes.shape[1]} de {Bulk.shape[1]} originales")

Genes seleccionados: 3192 de 15962 originales

In [11]:
df_top_genes.head()

,RPS4Y1,KRT19,VIM,S100P,EEF1A1,RPL18A,TACSTD2,RPS18,BASP1,RPS19,...,RAET1G,IGFL3,ANGPT1,RRP1B,C2ORF42,IFNGR1,TCEAL5,DUSP11,GNA11,MFSD6
DATA.683665,10.744227,3.405941,12.085272,3.336260,4.922896,3.062681,3.496972,4.855941,5.697826,4.038713,...,4.280225,3.394853,3.002283,8.001636,6.736740,7.831898,3.023507,7.876978,4.013298,7.270762
DATA.683667,12.410156,4.226230,11.661481,5.922569,6.533475,3.113093,3.027207,4.680126,5.011485,4.045782,...,3.581134,3.379538,3.001898,8.308363,6.997331,7.443246,3.019110,7.700416,8.309896,4.358078
DATA.684052,3.374015,4.032691,12.671484,3.477540,5.551361,2.892388,2.832211,3.884602,11.453684,3.944376,...,3.144730,3.307964,3.387063,7.957953,6.356331,6.905754,3.405001,7.464873,8.508063,4.455841
DATA.684057,12.822256,3.091820,10.667924,3.595975,5.277746,2.932124,2.932878,4.880253,9.359950,3.950865,...,3.840384,3.390363,2.994032,8.219939,6.465303,8.016595,4.280432,7.801002,7.849750,3.848845
DATA.684059,3.320986,3.492342,12.870585,4.567399,5.819835,2.982949,2.923305,3.888214,10.924775,3.717019,...,3.285166,3.518197,3.736578,7.958470,6.950287,8.002485,3.412617,6.972215,8.140381,4.290012

In [12]:
df_top_genes.to_csv("df_bulk_topGenes.csv")

# RESULTADOS

In [13]:
import scanpy as sc

adata = sc.read("/home/franciscojavier/Escritorio/TFG/scDEAL/save/adata/GSE110894_integrate_data_GSE110894_drug_I.BET.762_bottle_512_edim_256,128_pdim_128,64_model_DAEIntento2_dropout_0.1_gene_F_lr_0.5_mod_new_sam_upsampling.h5ad")  # reemplaza <para> por el sufijo real del modelo

WARNING: Your filename has more than two extensions: ['.BET', '.762_bottle_512_edim_256,128_pdim_128,64_model_DAEIntento2_dropout_0', '.1_gene_F_lr_0', '.5_mod_new_sam_upsampling', '.h5ad'].
Only considering the two last: ['.5_mod_new_sam_upsampling', '.h5ad'].
WARNING: Your filename has more than two extensions: ['.BET', '.762_bottle_512_edim_256,128_pdim_128,64_model_DAEIntento2_dropout_0', '.1_gene_F_lr_0', '.5_mod_new_sam_upsampling', '.h5ad'].
Only considering the two last: ['.5_mod_new_sam_upsampling', '.h5ad'].

In [14]:
y_true = adata.obs['sensitive']             # Etiqueta verdadera
y_pred = adata.obs['sens_label'].astype(int)  # Etiqueta predicha por el modelo

In [15]:
from sklearn.metrics import classification_report, accuracy_score, f1_score, precision_score, recall_score

print("Accuracy:", accuracy_score(y_true, y_pred))
print("F1 Score:", f1_score(y_true, y_pred, average='weighted'))
print("Precision:", precision_score(y_true, y_pred, average='weighted'))
print("Recall:", recall_score(y_true, y_pred, average='weighted'))

# Reporte completo
print(classification_report(y_true, y_pred))

Accuracy: 0.9640591966173362
F1 Score: 0.9640679436620386
Precision: 0.9652499686622353
Recall: 0.9640591966173362
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       685
           1       0.99      0.94      0.96       734

    accuracy                           0.96      1419
   macro avg       0.96      0.96      0.96      1419
weighted avg       0.97      0.96      0.96      1419